---
- name: What if we use yum_repository?
  yum_repository:
    baseurl: https://dl.fedoraproject.org/pub/epel/7Server/x86_64/
    description: "Epel release."
    name: epel-release
    state: present

- name: Install python-jenkins
  sudo: yes
  yum:
    name: python-jenkins
    state: installed
    
- jenkins_job:
    config: "{{ lookup('file', 'templates/config.xml') }}"
    name: job1
    #state: present
    password: admin
    url: http://35.174.139.176:8080
    user: admin
